"""
Django settings for City_Market project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os 
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR =os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-xe!j4v^vc*i174iq12(p^i&9ee*^&_@%rt!rj2o2qi$x1heh-d'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = ['127.0.0.1', '0c89-156-221-176-111.ngrok-free.app']

###########################################
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG","False").lower()=="true"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS").split()

######################################

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
     'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #custom apps
    'core.apps.CoreConfig',
    'Accounts.apps.AccountsConfig',
    'Product_Management_API.apps.ProductManagementApiConfig',
    'Order_Management_API.apps.OrderManagementApiConfig',
    'Payment_Management_API.apps.PaymentManagementApiConfig',
     "userauths.apps.UserauthsConfig",
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
     "django_htmx",
     "django_filters",
     'corsheaders',
     
]
CSRF_TRUSTED_ORIGINS = [
    "https://0c89-156-221-176-111.ngrok-free.app",
    "http://127.0.0.1:8000",
    "http://localhost",       # Another possible localhost origin
    "http://localhost:8158",

]

# CORS_ALLOWED_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "https://0c89-156-221-176-111.ngrok-free.app",
    "http://localhost:8000",  # Your frontend origin
    "http://localhost",       # Another possible localhost origin
    "null",                   # For file:// origin in local development
    "http://localhost:8158",
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF middleware
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_htmx.middleware.HtmxMiddleware",
]





ROOT_URLCONF = 'City_Market.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.categories' , 
                'core.context_processors.list_advertisements'

            ],
        },
    },
]


WSGI_APPLICATION = 'City_Market.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
      'default': {
      'ENGINE': 'django.db.backends.mysql',
      'NAME': 'market2',
      'USER': 'root',   
      'PASSWORD':'',   
      'HOST': '127.0.0.1',   
      'PORT': '3306',   
      'OPTIONS': {   
      'init_command':"SET sql_mode='STRICT_TRANS_TABLES'"  
        }  
    }
}
# DATABASES['default'] = dj_database_url.parse("postgresql://city_market_user:fYJHJVKQULjzOYx8LXujlK6DHOKsoRGq@dpg-cpsj74d6l47c73e6ldm0-a.oregon-postgres.render.com/city_market")

database_url =os.environ.get("DATABASES_URL")
DATABASES['default'] = dj_database_url.parse(database_url)

REST_FRAMEWORK = {
    
    'DEFAULT_AUTHENTICATION_CLASSES': (
        
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
    
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    "ROTATE_REFRESH_TOKENS": True,
    "ROTATE_ACCESS_TOKENS": True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/



STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR , "Media")
MEDIA_URL = "/Media/"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "CityMarket Admins",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "CityMarket Admins",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "CityMarket Admins",
    # "site_logo": "Logo7.png",
    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    # "login_logo": "Logo7.png",
    # CSS classes that are applied to the logo above
     "welcome_sign": "Welcome to City Market Admin page",
   
}
AUTH_USER_MODEL = 'userauths.User'   # to include custome usermodel instead default one 

# CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for CORS


