# Generated by Django 5.0.2 on 2024-03-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_field',
            new_name='birthday',
        ),
    ]
