# Generated by Django 5.0.2 on 2024-03-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_user_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(),
        ),
    ]
