# Generated by Django 5.0.2 on 2024-06-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_user_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(null=True),
        ),
    ]
