# Generated by Django 5.0.2 on 2024-03-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vid',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, to='core.address'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='authentic_rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='chat_resp_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='All Vendors'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_on_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
