# Generated by Django 5.0.2 on 2024-03-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='contact',
        ),
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
