# Generated by Django 5.0.2 on 2024-03-18 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_address_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_for_vendor', to='core.address'),
        ),
    ]
