# Generated by Django 5.0.2 on 2024-03-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vendor_default_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='address',
            new_name='addresses',
        ),
    ]
