# Generated by Django 5.0.2 on 2024-03-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_address_vendor_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
