# Generated by Django 5.0.2 on 2024-03-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Management_API', '0002_alter_cartorder_customer_and_more'),
        ('Product_Management_API', '0011_alter_product_vendor_alter_productfeedback_customer_and_more'),
        ('core', '0009_alter_country_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='default_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='default_address',
        ),
        migrations.DeleteModel(
            name='Advertisement_Board',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
