# Generated by Django 5.0.2 on 2024-03-03 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management_API', '0003_category_url_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_url',
            new_name='url',
        ),
    ]
