# Generated by Django 5.0.2 on 2024-03-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management_API', '0004_rename_product_url_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
