# Generated by Django 5.0.2 on 2024-03-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management_API', '0005_alter_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('', ''), ('in_review', 'In Review'), ('published', 'Published'), ('discontinued', 'Discontinued'), ('on_sale', 'On Sale'), ('in_review', 'In Review'), ('published', 'Published'), ('discontinued', 'Discontinued'), ('on_sale', 'On Sale')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_in_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
