# Generated by Django 5.0.2 on 2024-03-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management_API', '0007_alter_product_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('', ''), ('in_review', 'In Review'), ('published', 'Published'), ('discontinued', 'Discontinued'), ('on_sale', 'On Sale')], default='', max_length=250),
        ),
    ]
