# Generated by Django 5.0.2 on 2024-03-23 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management_API', '0011_alter_product_vendor_alter_productfeedback_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeedback',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='Product_Management_API.product'),
        ),
    ]
