# Generated by Django 5.0.2 on 2024-03-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management_API', '0012_alter_productfeedback_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfeedback',
            old_name='feedback',
            new_name='comment',
        ),
    ]
