# Generated by Django 5.0.2 on 2024-03-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management_API', '0015_alter_productfeedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
