# Generated by Django 5.0.2 on 2024-04-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management_API', '0016_alter_productfeedback_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Categories'),
        ),
        migrations.AlterField(
            model_name='productfeedback',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None, null=True),
        ),
    ]
