# Generated by Django 5.0.2 on 2024-03-01 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='Payment_methods')),
            ],
            options={
                'verbose_name': 'Payment Type',
            },
        ),
        migrations.CreateModel(
            name='User_Payment_Method',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('expiry_date', models.DateField()),
                ('is_default', models.BooleanField(default=False)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment_Management_API.payment_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Payment',
            },
        ),
    ]
