# Generated by Django 5.0.2 on 2024-03-01 07:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payment_Management_API', '__first__'),
        ('Product_Management_API', '__first__'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_status', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('new', 'New'), ('old', 'Old')], default='processing', max_length=20)),
                ('invoice_no', models.CharField(default='Auto-fill', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment_Management_API.user_payment_method')),
                ('product', models.ManyToManyField(to='Product_Management_API.product')),
                ('shipping_address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
            options={
                'verbose_name': 'Cart Order',
            },
        ),
        migrations.CreateModel(
            name='CartOrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=200)),
                ('order_qty', models.IntegerField(default=0)),
                ('item_status', models.CharField(blank=True, max_length=200)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product_Management_API.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order_Management_API.cartorder')),
            ],
            options={
                'verbose_name': 'Cart Order Item',
            },
        ),
    ]
