# Generated by Django 5.0.2 on 2024-05-05 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Management_API', '0003_cartorder_payment_status'),
        ('Product_Management_API', '0017_alter_category_image_alter_productfeedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='order_qty',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='paid_status',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='payment_mode',
            field=models.CharField(choices=[('COD', 'Cod'), ('CARD', 'Card')], default='COD', max_length=30),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product_Management_API.product'),
        ),
    ]
