# Generated by Django 5.0.2 on 2024-06-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Management_API', '0005_alter_cartorderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='product',
        ),
    ]
