# Generated by Django 5.0.2 on 2024-06-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Management_API', '0006_remove_cartorder_product'),
        ('Product_Management_API', '0017_alter_category_image_alter_productfeedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='product',
            field=models.ManyToManyField(to='Product_Management_API.product'),
        ),
    ]
