# Generated by Django 5.0.2 on 2024-06-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Management_API', '0007_cartorder_product'),
        ('Product_Management_API', '0017_alter_category_image_alter_productfeedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='item',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product',
            field=models.ManyToManyField(blank=True, to='Product_Management_API.product'),
        ),
    ]
