# Generated by Django 5.0.2 on 2024-06-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Order_Management_API', '0010_alter_cartorder_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.address'),
        ),
    ]
