# Generated by Django 5.0.2 on 2024-06-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Management_API', '0011_alter_cartorder_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='payment_mode',
            field=models.CharField(choices=[('Cod', 'Cod'), ('Card', 'Card')], default='Cod', max_length=30, null=True),
        ),
    ]
